# Generated by Django 5.2.5 on 2025-09-23 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_spark_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimirResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_content', models.TextField()),
                ('response_type', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mimir_responses', to='journal.spark')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
